### PR TITLE
Implement persistent collapsed comments

### LINKED ISSUE #84: Preserve collapsed comments
I'd like to be able to preserve the state of the comments page between reloads.  I collapse the threads that I don't want to see anymore.

I have implemented a basic persistent collapsed state. Should anyone be interested, I will push to my fork for review.  There are some design considerations that arise:

1. What is the expiration policy of the state objects in localstorage?
1. How is one notified of new comments within collapsed threads? I support extending the existing CommentTracker to add an indicator on the topmost visible parent.   (I think this is a generally useful design enhancement even outside of the collapsible feature.)

During the implementation, it turned out to be easier to have an abstract model of the thread.  I build  a comment graph during init() and use that to drive the UI changes.  This is likely to be useful for implementing other comment-related features.

### PR DESCRIPTION
**Pull request by ibejoeb**
Add persistent collapsed comments to resolve #84.

This also adds an abstract comment tree that can be used to drive other features.

### CODE REVIEW

**Comment by ibejoeb** [comment]
This also corrects issue #88.

@etcet : HNES is currently broken, as far as I can tell.  PR #90 fixes this also and is a very small patch.  It'd be nice to merge it if you don't want to go as far as I've gone.  However, I'm interested in continuing to improve it, so I hope you'll consider this PR.

**Comment by etcet** [comment]
First off: thanks for working on this and I'm sorry I waited so long. I hate to ask this but could you fix the current conflicts? 

There's the SVG arrows in https://github.com/etcet/HNES/pull/91 which we should keep and https://github.com/etcet/HNES/pull/90 which your code doesn't use. 

One thing I noticed when testing this is dead comments can't be collapsed. There's one on https://news.ycombinator.com/item?id=10339388 if you search for "[deleted]". Also, if you collapse the parent the dead comment remains visible.

**Comment by ibejoeb** [comment]
Yes, let me take a look.  I haven't seen the upstream code since this was made.

**Comment by etcet** [comment]
Thanks Joe. I've manually merged a pull request before but Github didn't give credit to the author as it did when it can be automatically merged. I don't want that to happen to you. This isn't time sensitive so please don't feel rushed. I promise to merge as soon as you're ready.

**Comment by ibejoeb** [comment]
I've done the majority of the merge.  I've incorporate #91.

On #90, what do you mean by "we should keep" it?  I implement it in CSS, which was resilient to the breakage anyway, as described here: https://github.com/etcet/HNES/pull/87#issuecomment-120775391.  Are you saying that you'd rather keep the jQuery implementation?  Or do you just want to preserve the exact styling, which looks like "[−] ckozlowski 10 days ago | parent"  I can definitely tweak mine to preserve that.

**Comment by ibejoeb** [comment]
Had to do a manual merged.  This PR is superseded by https://github.com/etcet/HNES/pull/98.

**Pull request closed without merging**
